require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'HwTransportReactNativeBleExample' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  use_frameworks!

  pod 'hw-transport-react-native-ble', :path => '../..'

  pod 'Starscream', '~> 4.0.0'
  pod 'BleTransport', :git => 'https://github.com/LedgerHQ/ios-ble.git'
  pod 'Bluejay', :git => 'https://github.com/DantePuglisi/bluejay.git', branch: 'fail-when-wrong-characteristic-property'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper' => '0.80.0' })
  post_install do |installer|
#    flipper_post_install(installer)
  end
end
